from backend_utils import VendorInfoBase  # noqa: E402

# from triton.runtime import driver  # noqa: E402

vendor_info = VendorInfoBase(
    vendor_name="sophgo",
    device_name="tpu",
    device_query_cmd="tpu-smi",
    dispatch_key="PrivateUse1",
    triton_extra_name="sophgo",
)

# driver.active.get_active_torch_device()

CUSTOMIZED_UNUSED_OPS = (
    # "abs",
    # "abs_",
    # "add",
    # "add_",
    # "addmm",
    # "angle",
    # "arange_start",
    # "arange_start",
    # "arange",
    # "batch_norm",
    "batch_norm_backward",
    # "bitwise_and_tensor",
    # "bitwise_and_tensor_",
    # "bitwise_and_scalar",
    # "bitwise_and_scalar_",
    # "bitwise_and_scalar_tensor",
    # "bitwise_not",
    # "bitwise_not_",
    # "bitwise_or_tensor",
    # "bitwise_or_tensor_",
    # "bitwise_or_scalar",
    # "bitwise_or_scalar_",
    # "bitwise_or_scalar_tensor",
    # "bmm",
    # "clamp",
    # "clamp_",
    # "clamp_tensor",
    # "clamp_tensor_",
    # "cos",
    # "cos_",
    # "pad",
    # "constant_pad_nd",
    # "cumsum",
    # "cummin",
    # "true_divide",
    # "true_divide_",
    # "true_divide",
    # "true_divide_",
    # "div_mode",
    # "div_mode_",
    # "div_mode",
    # "div_mode_",
    # "true_divide",
    # "true_divide_",
    # "true_divide",
    # "true_divide_",
    # "div_mode",
    # "div_mode_",
    # "div_mode",
    # "div_mode_",
    # "true_divide",
    # "true_divide_",
    # "true_divide",
    # "true_divide_",
    # "floor_divide",
    # "floor_divide_",
    # "floor_divide",
    # "floor_divide_",
    # "remainder",
    # "remainder_",
    # "remainder",
    # "remainder_",
    # "remainder",
    # "dropout",
    "dropout_backward",
    # "erf",
    # "erf_",
    # "embedding",
    "embedding_backward",
    # "eq",
    # "eq_scalar",
    # "exp",
    # "exp_",
    # "exponential_",
    # "ge",
    # "ge_scalar",
    # "gelu",
    # "gelu_",
    "gelu_backward",
    # "group_norm",
    "group_norm_backward",
    # "weight_norm_interface",
    "weight_norm_interface_backward",
    # "gt",
    # "gt_scalar",
    # "isfinite",
    # "isin",
    # "isin",
    # "isin",
    # "isinf",
    # "isnan",
    # "minimum",
    # "maximum",
    # "layer_norm",
    "layer_norm_backward",
    # "le",
    # "le_scalar",
    # "lt",
    # "lt_scalar",
    # "log",
    # "rms_norm",
    # "rand",
    # "randn",
    # "rand_like",
    # "randn_like",
    # "zeros",
    # "ones",
    # "full",
    # "zeros_like",
    # "ones_like",
    # "full_like",
    # "linspace",
    # "resolve_neg",
    # "resolve_conj",
    # "normal_tensor_float",
    # "normal_float_tensor",
    # "normal_tensor_tensor",
    # "uniform_",
    # "mean",
    # "mean_dim",
    # "mm",
    # "mul",
    # "mul_",
    # "multinomial",
    # "mv",
    # "nan_to_num",
    # "ne",
    # "ne_scalar",
    # "neg",
    # "neg_",
    # "pow_scalar",
    # "pow_tensor_scalar",
    # "pow_tensor_scalar_",
    # "pow_tensor_tensor",
    # "pow_tensor_tensor_",
    # "reciprocal",
    # "reciprocal_",
    # "relu",
    # "relu_",
    # "rsqrt",
    # "rsqrt_",
    # "sigmoid",
    # "sigmoid_",
    "sigmoid_backward",
    # "silu",
    # "silu_",
    "silu_backward",
    # "sin",
    # "sin_",
    # "softmax",
    "softmax_backward",
    "sort",
    # "sub",
    # "sub_",
    # "tanh",
    # "tanh_",
    "tanh_backward",
    # "threshold",
    "threshold_backward",
    # "triu",
    # "var_mean",
    # "vector_norm",
    # "where_self_out",
    # "where_self",
    # "where_scalar_self",
    # "where_scalar_other",
    # "max",
    # "max_dim",
    # "min",
    # "min_dim",
    # "amax",
    # "argmax",
    # "argmin",
    # "prod",
    # "prod_dim",
    # "sum",
    # "sum_dim",
    # "scaled_dot_product_attention",
    # "all",
    # "all_dim",
    # "all_dims",
    # "any",
    # "any_dim",
    # "any_dims",
    # "quantile",
    # "log_softmax",
    "log_softmax_backward",
    # "nll_loss_forward",
    "nll_loss_backward",
    # "nll_loss2d_forward",
    "nll_loss2d_backward",
    # "scatter",
    # "scatter",
    # "gather",
    "gather_backward",
    # "isclose",
    # "allclose",
    # "fill_scalar",
    # "fill_tensor",
    # "fill_scalar_",
    # "fill_tensor_",
    # "flip",
    # "slice_scatter",
    # "select_scatter",
    # "index_select",
    # "tile",
    # "masked_fill",
    # "masked_fill",
    # "masked_fill_",
    # "masked_fill_",
    # "_unique2",
    # "_upsample_bicubic2d_aa",
    # "upsample_nearest2d",
    # "nonzero",
    # "repeat",
    # "masked_select",
    # "stack",
    # "hstack",
    # "cat",
    # "repeat_interleave_self_int",
    # "vstack",
    # "repeat_interleave_tensor",
    # "repeat_interleave_self_tensor",
    # "randperm",
    # "diag",
    # "diag_embed",
    "diagonal_backward",
    # "index_add",
    # "count_nonzero",
    # "logical_or",
    # "logical_and",
    # "polar",
    # "logical_xor",
    # "logical_not",
    # "dot",
    # "kron",
    # "elu",
    # "index_put_",
    # "index_put",
    # "contiguous",
    # "log_sigmoid",
    # "vdot",
    # "mse_loss",
    "to_copy",
    "index",
)


__all__ = ["*"]
